version=0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pavlov-webhook-telegram"
s3_bucket = "telegram-bot-bucket"
s3_prefix = "my-s3-prefix"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
